### ISSUE TITLE
bootstrapping example(s) in the vignette file

### ISSUE THREAD

**Issue by daaronr** [jeff-hughes/paramtest#1]
Not sure if this should be called an 'issue', but I read the very [nice vignette ](https://cran.r-project.org/web/packages/paramtest/vignettes/Simulating-Power.html), and had something I wanted to consult you on.

The Bootstrapping example you give is *not* a power calculation; I know you realise this, but it was confusing in reading it in this context (because the vignette is titled 'simulating power').

 However, there are situations in which I *would* want to resample from existing/prior data to do an (ex-ante) power calculation. 

E.g., for a marketing experiment...

You may have a distribution of previous bids on items on Ebay for the last 10 years. 

You want to measure the impact of an early bid on the sales price by assigning *future* pages into treatments and controls and making early bids on the treatment pages

Given your proposed blocked-randomisation design, you want to know 
     - how much power you will get for a particular sample size and a particular treatment effect size
     - how many treatment pages you need to bid on to achieve 80% power...
     - what the minimum detectable treatment effect size will be

So in doing a simulated power calc you would want to do something like... in each simulation... 
- draw randomly from the historical data
- assign (hypothetically) to treatment/control 
- for treatment observations, compute the hypothetical outcome given the treatment effect size you are testing
- run the statistical test on this hypothetical data

Do you have or know of any code examples for this sort of bootstrapped power calculation (with grid search of course)? Is paramtest suitable for it> 

The main advantage of doing this data-based simulation over a purely abstract simulated one would be that you would be doing this using a distribution that more closely resembles the true distribution (of the control observations at least)

**Comment by daaronr** [comment]
(By the way reading this over again, I believe the vignette is a power calculation, but it's unclear to me the context in which one would want to do such a calculation, rather than what I am proposing.)

**Comment by jeff-hughes** [comment]
Hi there, thanks for the comment! I will admit that I mostly put the bootstrapping example in there to highlight that the package does support bootstrapping as well, but I agree that it's not really a typical case for power simulation. The package is really, more generally, about repeatedly running a function while varying parameters, which is also useful in cases like machine learning, where you frequently want to iterate a model over various hyperparameters to test how they operate. The bottom line is that I included the bootstrapping because it was easy to implement and I figured I might as well -- even if I couldn't think of a particular use case, it could be useful to someone.

At any rate, I think the idea you have is certainly interesting. It seems quite similar in principle to a typical power simulation -- you're randomly sampling from a distribution, and adding an estimated treatment effect to simulate the results. The only difference between your approach and the typical power simulation you might see (including most of the examples in my vignette) is that you are generating data from an empirical distribution rather than a theoretical one. I think it could certainly be beneficial, provided that you have enough initial data. Bootstrapping would help to alleviate that somewhat given its fairly relaxed assumptions, but it may only get you so far. With very limited data, you might still find yourself estimating the underlying theoretical distribution poorly. In that case, you could potentially fit a distribution of some kind (e.g., normal, poisson) to the data, estimate the parameters of the distribution from the data, and then use the theoretical distribution within your simulations. But if you have so little data that bootstrapping is difficult, then estimating a model is likely not much better. You might be better off just making assumptions about the general parameters and forgoing the data entirely.

Anyway, I think given a reasonable amount of data, what you're proposing makes complete sense. If you have the data, you might as well use it! I don't know of any particular code you could use as a template, but you should at least be able to use the bootstrap function with the paramtest package to handle that portion of it. It basically provides the bootstrapped data set to your function, and you can do whatever you want with it. The package is intentionally quite minimal to keep things fairly flexible. With a simple model, you might just add a flat amount (or multiplier) to each "treatment" data point and then run your test. If you have more complex predictions, you might use a combination of the empirical data and some theoretical distributions for other variables that might impact the predictions you're trying to make. Maybe you set your treatment effect to `y = y + b1*treatment + b2*var`, where `y` is your original bid price, `b1` is the treatment effect size, `treatment` is a dummy code indicating treatment/control, and `b2` is the effect size of another predictor `var`, generated from a normal distribution, for example. So you take your original bid price, adjust according to your assumed effect sizes, and then run your statistical tests. It's difficult to design the whole thing in the abstract like this, but hopefully it's clear that this could be scaled up to more complex models if desired, with a bit of creativity. I wish I had a good, concrete example of it that you could follow, but you're essentially feeding in your bootstrapped data into the data generating process, so much of what appears in the vignettes might still be applicable.

My suggestion would be to play around with some toy data, or with a subset of your data, and get the logic of your simulation right. Start with a single iteration to make sure you can generate your data properly, run the statistical tests successfully, and get the output you want. Then you can add the varying parameters, etc. and scale up. I think it's quite doable with paramtest, but obviously the specifics of the model you're interested in running make a big difference -- so it's hard to give any more detailed advice!

**Comment by daaronr** [comment]
> The only difference  ... is that you are generating data from an empirical distribution rather than a theoretical one.

Yes, and I need to locate and dig into the literature considering this sort of approach; I would imagine this must be a fairly common practice in field and marketing/web-based experiment design

>   I think it could certainly be beneficial, provided that you have enough initial data. 

Being web-based, there is loads of initial data in my case (at least, it 'feels' like loads of data... tens of thousands of observations relative to my 'treatment/control' sample of perhaps several hundred)

>  With very limited data, you might still find yourself estimating the underlying theoretical distribution poorly.

I assume you mean the *true* underlying distribution ... I don't have a strong theory for what shape this should take

>    In that case, you could potentially [B] fit a distribution of some kind (e.g., normal, poisson) to the data, estimate the parameters of the distribution from the data, and then use the theoretical distribution within your simulations. But if you have so little data that bootstrapping is difficult, then estimating a model is likely not much better. [C] You might be better off just making assumptions about the general parameters and forgoing the data entirely.

I'll considered each of these approaches; as this is social science in a natural (not lab) context, there is little justification for imposing any values for the distribution parameters; these would naturally come from the data, so one might as well do this explicitly. Thus, I think [B] would be preferred to [C], but the approach I proposed above ("[A]") is likely to be even better. I also suppose there may be some scope for validating the power calculation itself by splitting the prior data into training/testing groups.

> ....given a reasonable amount of data, what you're proposing makes complete sense ... you should at least be able to use the bootstrap function with the paramtest package to handle that portion of it. It basically provides the bootstrapped data set to your function, and you can do whatever you want with it. The package is intentionally quite minimal to keep things fairly flexible. With a simple model, you might just add a flat amount (or multiplier) to each "treatment" data point and then run your test. 

This is precisely what I'm working on and I'll report back what I come up with. The (minor) challenge is that your bootstrap code seems to bootstrap a sample of the size as the original data set, while I would be considering much smaller 'experimental trials.' But I'm sure I can figure out a way to do this filtering/subsetting that hopefully won't waste too much processing time.  

Here's what I've written so far; it seems to run OK (will adapt it to take a generic outcome variable, and to accommodate other experimental designs etc)...

```

t_func_boot <- function(data,indices,N,TE,tshare=0.5,lin=1,prop=0) { #function must take data, indices as 1st two args; see 'boot' package docs;
  #N sample size being considered,
  #TE is the treatment effect being considered; 
  #tshare is share allocated to treatment 
  #lin and prop are booleans for a linear or proportional treatment effect
  
  sample_data <- data[indices, ] %>%
    dplyr::select(weight) %>%
    dplyr::sample_n(N,replace=FALSE) #take N rows of bootstrap sampled data and shuffle
  
  ctrlGroup <- filter(sample_data, (row_number() <= (n()*tshare))) #random assignment; adapt to blocked-random designs etc.
  treatGroup <- filter(sample_data, (row_number() > (n()*tshare))) %>%
    mutate(weight := weight*(1+prop*TE)+lin*TE)
  t <- t.test(treatGroup, ctrlGroup, var.equal=TRUE) #replace with other potential tests based on pre-analysis plan
  stat <- t$statistic
  p <- t$p.value
  return(c(t=stat, p=p, sig=(p < .05)))
}

# example using built-in dataset PlantGrowth
power_ttest_boot <- run_test(t_func_boot, n.iter=100, output='data.frame', boot=TRUE,
                             bootParams=list(data=PlantGrowth,N=20,TE=0.7))
results(power_ttest_boot) %>%
  summarise(power=mean(sig))

```

**Comment by daaronr** [comment]
By the way, there is an somewhat-related discussion on StackExchange [here](https://stats.stackexchange.com/a/70696/174812), but it also seems to be somewhat misguided as a power calculation, in that it is basically asking "how much more data that looks exactly like the data I have now would be needed for this to be deemed statistically significant?"  

I think that approach implicitly assumes that the treatment effect is *exactly* equal to the treatment effect observed in the prior data; not sure how that is justified.

(And in my case I have *no* prior treatment data; the power test will be considering an 'effect of a minimum relevant size' ... or determining how small an effect we can hope to detect.)

**Comment by jeff-hughes** [comment]
Yes I agree with your "ranking", that the provided you have sufficient data then [A] would be preferable to [B], which would be preferable to [C]. I was just mentioning other options because I don't think the bootstrapping approach is always preferable. I've certainly seen people try to bootstrap with very little data as if it is a magic solution to the issue -- but of course if your small sample is systematically biased, your bootstrapped sample is just going to reflect that.

Anyway, you're right that it might be a bit of a complication to use the boot function in the paramtest package, as it is assuming you want a sample of the same size. As you're no doubt aware, that would be the typical approach to bootstrapping. The underlying code is using the `boot()` function (from the "boot" package that comes with base R), which doesn't even have an option for specifying a sample size. So perhaps that's not the best option. The code you link to from StackExchange actually gives you a template for a better option using the `sample()` function, as that allows you to sample with replacement but specify a given size. It should be easy enough to put that into your custom function -- instead of sampling from a normal distribution, the `sample()` function now becomes your data generating function, and you can go from there.

One thing to note is that R doesn't always play well when it comes to parallelizing code. It's fine while you're just building things up, but once you get to your full-scale test you'll probably want to use the `parallel` option that can dramatically speed up the simulations. It works great when everything your custom function needs is built within the function itself (i.e., you're generating the data and running the tests inside the function), but when using external data you could run into an issue. It's been a while since I've done this so I can't be sure that it's an issue, but basically the parallel processing sets up child processes that run on your multiple processor cores. These child processes don't have access to the same R environment as the parent process (or else all your data, etc. would have to be loaded for each one, which would increase the amount of time it takes), but you can pass specific variables to them. So the data you are bootstrapping from might need to be passed to your child processes. This StackOverflow answer has some code you can use: https://stackoverflow.com/a/12020082 
This method requires you to set up your clusters manually unfortunately, but that's one line of code. But then the `grid_search()` accepts the `cl` argument where you pass it your clusters. So you set up the clusters, export the data to each of them, and then pass that along to the actual simulation. Hope that makes sense.

**Comment by daaronr** [comment]
Thanks, I'll work on this. For now the code posted above is working reasonably fast but I haven't tried grid search by effect size and N, nor put in blocked randomization.

I don't think the term 'bootstrapping' represents what I'm doing, although there are parallels; bootstrapping is usually about a robust way to estimate the standard error of a single estimator, with an eye towards the type-I error (size of the test).  Here we're trying to assess the power of a design as a function of sample size, effect size, and blocking method (and estimation technique)... although I am *using* samples data drawn from previous data (on the 'control' only) as in bootstrapping.

**Comment by jeff-hughes** [comment]
Yeah I agree, bootstrapping is not the correct term. You're doing a Monte Carlo simulation, making darws from real data. But you're right, it's got some similarity to bootstrapping.

Anyway, I'm happy to continue helping out by email, but for now I think I will close this issue. Best of luck!

**Comment by daaronr** [comment]
Understood and thanks.  For the sake of future readers of this thread, here is the code I've come up with for now:

```

#partly from https://stats.stackexchange.com/questions/37796/calculating-necessary-sample-size-using-bootstrap

power_data <- function(ds,reps,yvar,N,tshare=0.5,linTE=0,propTE=0,alpha=0.05) {
  #todo -- add argument 'testname'
  #N sample size being considered,
  #tshare is share allocated to treatment 
  #lin and prop are  linear or proportional treatment effects
  
  #Prelims for tidy eval
    yvar <-  enquo(yvar) #takes the argument and makes it into a 'quosure'... like quoting it, so dplyr commands can use it 
    yvar_name <-  quo_name(yvar) #quotes this argument in a way such that we can use it as a  *name*
    #testname <- enquo(testname)
    
  #Do the following simulation  'reps' number of times 
    results  <- sapply(1:reps, function(r) {
  
    #Sample size N from data for each iteration
      exp_sample <- sample_n(ds, size=N, replace=TRUE) #WHY is it duplicating columns??
        
    #"Selection of control and treatment group: random assignment"; todo-- adapt to blocked-random designs etc.
        exp_sample <- exp_sample %>%
          mutate(
            d_t = row_number() <= (n()*tshare) #assign treatment dummy
            ) %>% #"Add treatment effects to treatgroup"
             mutate(!! yvar_name :=  ifelse(
               d_t=="TRUE",!! yvar *(1+propTE)+linTE, !!yvar)) %>%
                mutate(yv = !! yvar) %>% #reassign variable because I couldn't figure out how to get the unquoted argument to work in tests below  
            dplyr::select(yv, d_t) 
        
    #Do test   
        test <- exp_sample %>% 
          do(tidy(
          t.test(yv ~ d_t, data=., paired=FALSE))) #todo: adjust to make the test and its parameters function arguments
          #swapping in wilcox.test above works too
        test$p.value
    })
    sum(results<0.05)/reps
}

# examples using our data
pwr_n400_L50_p15 <- power_data(ds=Fdd_f,reps=100,yvar=outcome1,N=400,tshare=0.5,linTE=50,propTE=0.15,alpha=0.05)

pwr_n400_L100 <- power_data(ds=Fdd_f,reps=100,yvar=outcome1,N=400,tshare=0.5,linTE=100,propTE=0,alpha=0.05)

pwr_n400_p20_ct <- power_data(ds=Fdd_f,reps=100,yvar=outcome2,N=400,tshare=0.5,propTE=0.2,alpha=0.05)

pwr_n400_L3_ct <- power_data(ds=Fdd_f,reps=100,yvar=outcome2,N=400,tshare=0.5,linTE=3,propTE=0,alpha=0.05)
```
